
-- Таблица категорий
CREATE TABLE IF NOT EXISTS categories (
                            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                       id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                       name VARCHAR(250) NOT NULL,
                       email VARCHAR(254) NOT NULL UNIQUE
);

-- Таблица локаций
CREATE TABLE IF NOT EXISTS locations (
                           id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           lat FLOAT NOT NULL,
                           lon FLOAT NOT NULL
);

-- Таблица событий
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    lat DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90.0 AND 90.0),
    lon DOUBLE PRECISION NOT NULL CHECK (lon BETWEEN -180.0 AND 180.0),
    event_date TIMESTAMP NOT NULL,
    category_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL,
    state VARCHAR(20) NOT NULL CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
    paid BOOLEAN NOT NULL,
    created_on TIMESTAMP,
    published_on TIMESTAMP,
    participant_limit INT DEFAULT 0,
    request_moderation BOOLEAN DEFAULT false,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (initiator_id) REFERENCES users(id)
    );

-- Таблица заявок на участие
CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    created TIMESTAMP NOT NULL,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_requester FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Таблица подборок событий
CREATE TABLE IF NOT EXISTS compilations (
                                            compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            pinned BOOLEAN NOT NULL,
                                            title VARCHAR(255) NOT NULL
);

-- Связь между подборками и событиями
CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations(compilation_id),
    FOREIGN KEY (event_id) REFERENCES events(id)
);